services:
  postgres:
    image: postgres:16-alpine
    container_name: garment-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: garment_inventory
    volumes:
      - garment_pg_data:/var/lib/postgresql/data

volumes:
  garment_pg_data:
